# Actuator
info:
  app:
    name: "This is task service"
    version: "1.0.0"
    description: "This task service manages tasks!"

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
#  prometheus:
#    metrics:
#      export:
#        enabled: true