server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: productserviceapp
          uri: http://localhost:8081/
          predicates:
            - Path=/v1/products/**
            #- Method=GET
#          filters:
#            - RewritePath=/tasks/(?<segment>.*)/(?<segment2>.*), /tasks/all
        - id: clientserviceapp
          uri: http://localhost:8082/
          predicates:
            - Path=/v1/clients/**
            #- Method=POST

